### ISSUE TITLE
Suggestion - Way to import mods through other apps

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#53] opened 2016-08-27 08:53 UTC
As we know, there is some apps in google playstore that can import mods to BlockLauncher, it makes a prompt and asks you if you wanna import it. My suggestion is that you should add this to ToolBox too 👍

**Comment by ghost** [comment] 2016-09-13 13:29
Really... ModPE?

**Comment by slice** [comment] 2016-09-14 01:02
Yes.

**Comment by TheBigHacker0100** [comment] 2016-09-21 16:22
What do you mean with 'blocklauncher compat'?

**Comment by slice** [comment] 2016-09-21 17:26
@TheBigHacker0100 BlockLauncher compatability.

**Comment by ghost** [comment] 2016-10-11 14:34
This is not about BlockLauncher compatibility.........................

**Comment by MCMrARM** [comment] 2017-01-07 13:43
This is a duplicate of https://github.com/MCMrARM/toolbox-issue-tracker/issues/38

**Comment by ghost** [comment] 2017-01-07 13:44
rip

**Closed as completed by MCMrARM** 2017-01-07 13:43 UTC
Labels: T-Suggestion, T-ModPE, P-BlocklauncherCompat
